"""Which hosts never reach a miner, and why.

Categories come from the UT1 blacklists (Universite Toulouse 1). Matching is on the exact host:
UT1 lists subdomains such as `<name>.wordpress.com`, so collapsing entries to their registrable
domain would exclude wordpress.com itself.
"""

from __future__ import annotations

import re

# Removed outright: unsafe, or no article-shaped content to index.
UT1_EXCLUDE = (
    "adult",
    # Bank portals are login screens with nothing to index, and their intrusion detection
    # treats a robots.txt fetch followed by two sitemap probes as a scan.
    "bank",
    "malware",
    "phishing",
    "cryptojacking",
    "stalkerware",
    "ddos",
    "hacking",
    "warez",
    "gambling",
    "shortener",
    "publicite",
    "dynamic-dns",
    "doh",
    "residential-proxies",
    "social_networks",
    "forums",
    "chat",
    "webmail",
    "filehosting",
)

# Recorded on the row, not excluded: too many legitimate sites inside them.
UT1_FLAG = (
    "dating",
    "mixed_adult",
    "lingerie",
    "drugs",
    "violence",
    "vpn",
    "redirector",
    "remote-control",
    "download",
    "translation",
    "webhosting",
    "sect",
    "fakenews",
)

UT1_TYPE_HINT = {
    "press": "news",
    "blog": "blog",
    "shopping": "company",
    "jobsearch": "company",
}

# Search engines, social platforms, media apps and user-content sites: their pages are generated
# per session or per user and are not worth a crawl budget.
DYNAMIC_PLATFORMS = {
    "google.com",
    "google.co.uk",
    "google.de",
    "bing.com",
    "duckduckgo.com",
    "yandex.ru",
    "yandex.net",
    "baidu.com",
    "naver.com",
    "sohu.com",
    "ask.com",
    "yahoo.com",
    "aol.com",
    "youtube.com",
    "youtube-nocookie.com",
    "googlevideo.com",
    "ytimg.com",
    "vimeo.com",
    "dailymotion.com",
    "twitch.tv",
    "kick.com",
    "netflix.com",
    "hulu.com",
    "disneyplus.com",
    "spotify.com",
    "soundcloud.com",
    "deezer.com",
    "pandora.com",
    "bandcamp.com",
    "facebook.com",
    "fbcdn.net",
    "instagram.com",
    "cdninstagram.com",
    "threads.net",
    "twitter.com",
    "x.com",
    "t.co",
    "twimg.com",
    "tiktok.com",
    "tiktokcdn.com",
    "tiktokv.com",
    "linkedin.com",
    "licdn.com",
    "pinterest.com",
    "pinimg.com",
    "reddit.com",
    "redd.it",
    "tumblr.com",
    "vk.com",
    "ok.ru",
    "weibo.com",
    "qq.com",
    "bsky.app",
    "mastodon.social",
    "snapchat.com",
    "discord.com",
    "discord.gg",
    "telegram.org",
    "telegram.me",
    "t.me",
    "whatsapp.com",
    "whatsapp.net",
    "wa.me",
    "quora.com",
    "stackexchange.com",
    "roblox.com",
    "steamcommunity.com",
    "epicgames.com",
    "playstation.net",
    "amazon.com",
    "ebay.com",
    "aliexpress.com",
    "alibaba.com",
    "etsy.com",
    "temu.com",
    "shein.com",
    "walmart.com",
    "target.com",
    "wish.com",
    "mercadolibre.com",
    "onlyfans.com",
    "patreon.com",
    "ko-fi.com",
    "buymeacoffee.com",
    "gofundme.com",
    "change.org",
    "eventbrite.com",
    "meetup.com",
    "booking.com",
    "airbnb.com",
    "expedia.com",
    "tripadvisor.com",
    "indeed.com",
    "glassdoor.com",
    "monster.com",
    "zillow.com",
    "craigslist.org",
    "dropbox.com",
    "mega.co.nz",
    "mediafire.com",
    "wetransfer.com",
    "box.com",
    "imgur.com",
    "flickr.com",
    "500px.com",
    "unsplash.com",
    "pixabay.com",
    "giphy.com",
    "issuu.com",
    "slideshare.net",
    "scribd.com",
    "academia.edu",
    "researchgate.net",
    "gmail.com",
    "outlook.com",
    "hotmail.com",
    "office365.com",
    "icloud.com",
    "mail.ru",
    "zoom.us",
    "webex.com",
    "teamviewer.com",
    "anydesk.com",
    "calendly.com",
    "trello.com",
    "surveymonkey.com",
    "jotform.com",
    "typeform.com",
    "airtable.com",
    "notion.so",
}

# Infrastructure: CDNs, resolvers, certificate authorities, registrars, ad and analytics endpoints.
INFRASTRUCTURE = {
    "gstatic.com",
    "googleapis.com",
    "googleusercontent.com",
    "googletagmanager.com",
    "google-analytics.com",
    "googlesyndication.com",
    "googleadservices.com",
    "doubleclick.net",
    "gvt1.com",
    "gvt2.com",
    "g.co",
    "goo.gl",
    "g.page",
    "ggpht.com",
    "app-measurement.com",
    "googledomains.com",
    "googleblog.com",
    "amazonaws.com",
    "cloudfront.net",
    "amazon-adsystem.com",
    "media-amazon.com",
    "ssl-images-amazon.com",
    "a2z.com",
    "amzn.to",
    "azure.com",
    "azureedge.net",
    "azurefd.net",
    "windows.net",
    "windows.com",
    "windowsupdate.com",
    "msftncsi.com",
    "msftconnecttest.com",
    "live.com",
    "office.com",
    "office.net",
    "microsoftonline.com",
    "sharepoint.com",
    "skype.com",
    "msn.com",
    "apple-dns.net",
    "aaplimg.com",
    "icloud-content.com",
    "apple.co",
    "cloudflare.com",
    "cloudflare-dns.com",
    "cloudflareinsights.com",
    "akamai.net",
    "akamaiedge.net",
    "akam.net",
    "edgekey.net",
    "edgesuite.net",
    "fastly.net",
    "fastly-edge.com",
    "jsdelivr.net",
    "unpkg.com",
    "cdnjs.com",
    "bootstrapcdn.com",
    "gravatar.com",
    "wp.com",
    "w.org",
    "gmpg.org",
    "domaincontrol.com",
    "gtld-servers.net",
    "root-servers.net",
    "ntp.org",
    "registrar-servers.com",
    "dns-parking.com",
    "dnsowl.com",
    "afternic.com",
    "dropcatch.com",
    "expireddomains.com",
    "hugedomains.com",
    "godaddy.com",
    "namecheap.com",
    "gandi.net",
    "bit.ly",
    "tinyurl.com",
    "linktr.ee",
    "about.me",
    "forms.gle",
    "ezviz7.com",
    "hicloudcam.com",
    "appsflyersdk.com",
    "applovin.com",
    "adjust.com",
    "branch.io",
    "onelink.me",
    "sentry.io",
    "newrelic.com",
    "hotjar.com",
    "criteo.com",
    "taboola.com",
    "outbrain.com",
    "adnxs.com",
    "casalemedia.com",
    "2mdn.net",
    "omtrdc.net",
    "pv-cdn.net",
    "gwfb.net",
    "supertms.com",
    "digicert.com",
    "letsencrypt.org",
    "globalsign.com",
    "sectigo.com",
    "identrust.com",
    "aboutads.info",
    "allaboutcookies.org",
    "networkadvertising.org",
    "cookiedatabase.org",
    "privacyshield.gov",
    "youronlinechoices.com",
    "addtoany.com",
    "sharethis.com",
    "addthis.com",
    "lsrelayaccess.com",
    "imcmdb.net",
    "prodregistryv2.org",
    "one.one",
    "purl.org",
    "doi.org",
    "schema.org",
    "example.com",
    "example.org",
    "example.net",
    "in-addr.arpa",
    "ip6.arpa",
    "aliyuncs.com",
    "myqcloud.com",
    "myhuaweicloud.com",
    "mybluehost.me",
    "cpanel.net",
    "nginx.org",
    "nginx.com",
    "f5.com",
    "macromedia.com",
}

INFRASTRUCTURE_NAME = re.compile(
    r"(^|[.-])(cdn|static|assets|edge|akamai|cloudfront|fastly|azureedge|googleapis|gstatic"
    r"|tagmanager|analytics|doubleclick|syndication|adsystem|adservice|adserver|pixel"
    r"|tracking|telemetry|metrics|ocsp|crl|nameserver|ns\d|dns|ntp|mirror|mirrors)([.-]|$)",
    re.I,
)


def exclusion_reason(
    host: str,
    categories: dict[str, set[str]],
    tld_group: str,
    adult: set[str] = frozenset(),
) -> str | None:
    if host in adult:
        return "adult_list"
    for category in UT1_EXCLUDE:
        if host in categories.get(category, ()):
            return f"ut1_{category}"
    if host in DYNAMIC_PLATFORMS:
        return "dynamic_platform"
    if host in INFRASTRUCTURE:
        return "infrastructure"
    if INFRASTRUCTURE_NAME.search(host):
        return "infrastructure_name"
    if tld_group == "other_cctld":
        return "non_english_tld"
    return None
