-- Control plane: which domains we know, and the schedule for the sitemaps they publish.
-- The URLs themselves live in the frontier (parquet), not here.

CREATE SCHEMA IF NOT EXISTS bot;
SET search_path TO bot;

CREATE TABLE IF NOT EXISTS domains (
    host            text PRIMARY KEY,
    rank            integer,
    tld_group       text,
    type_hint       text,
    status          text NOT NULL DEFAULT 'candidate',
    reject_reason   text,
    robots_status   integer,
    robots_allows   boolean,
    crawl_delay     real,
    language        text,
    declared_lang   text,
    home_chars      integer,
    sitemap_url     text,
    sitemap_kind    text,
    url_count       bigint NOT NULL DEFAULT 0,
    checked_at      timestamptz,
    next_check_at   timestamptz,
    CONSTRAINT domains_status_check
        CHECK (status IN ('candidate', 'qualified', 'rejected'))
);

CREATE INDEX IF NOT EXISTS domains_candidates_idx
    ON domains (rank NULLS LAST) WHERE status = 'candidate';
CREATE INDEX IF NOT EXISTS domains_recheck_idx
    ON domains (next_check_at) WHERE status = 'qualified';

-- One row per sitemap file we schedule. Children we have not walked are not stored: they are
-- re-derived from their parent index, which costs one request.
CREATE TABLE IF NOT EXISTS sitemaps (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host              text NOT NULL,
    url               text NOT NULL UNIQUE,
    kind              text,
    parent_id         bigint,
    depth             smallint NOT NULL DEFAULT 0,
    url_count         integer NOT NULL DEFAULT 0,
    child_count       integer NOT NULL DEFAULT 0,
    changefreq_mode   text,
    status            text NOT NULL DEFAULT 'pending',
    error             text,
    lastmod           timestamptz,
    etag              text,
    last_modified     text,
    content_hash      text,
    fetched_at        timestamptz,
    changed_at        timestamptz,
    unchanged_checks  smallint NOT NULL DEFAULT 0,
    check_interval_s  integer NOT NULL DEFAULT 86400,
    next_check_at     timestamptz,
    CONSTRAINT sitemaps_status_check
        CHECK (status IN ('pending', 'ok', 'error', 'skipped'))
);

CREATE INDEX IF NOT EXISTS sitemaps_host_idx ON sitemaps (host);
CREATE INDEX IF NOT EXISTS sitemaps_due_idx
    ON sitemaps (next_check_at) WHERE status = 'ok';
CREATE INDEX IF NOT EXISTS sitemaps_parent_idx ON sitemaps (parent_id);

-- Where each frontier parquet file came from, so a rebuild knows what it already has.
CREATE TABLE IF NOT EXISTS frontier_files (
    path        text PRIMARY KEY,
    host_bucket smallint NOT NULL,
    url_count   integer NOT NULL,
    bytes       bigint NOT NULL,
    written_at  timestamptz NOT NULL DEFAULT now()
);
