-- Control plane for the crawler: which domains exist, what each is, and when each is next due.

CREATE SCHEMA IF NOT EXISTS bot;
SET search_path TO bot;

-- next_due_at is a fact about a domain, not a queue entry; the loop reads it in batches.
CREATE TABLE IF NOT EXISTS domains (
    host              text PRIMARY KEY,
    rank              integer,
    tld_group         text,

    state             text NOT NULL DEFAULT 'new',
    state_reason      text,
    failures          smallint NOT NULL DEFAULT 0,
    next_due_at       timestamptz DEFAULT now(),
    last_ok_at        timestamptz,
    checked_at        timestamptz,
    canonical_host    text,

    robots_checked_at timestamptz,
    robots_status     integer,
    robots_allows     boolean,
    crawl_delay       real,

    language          text,
    declared_lang     text,
    home_chars        integer,
    url_count         bigint NOT NULL DEFAULT 0,

    category          text,
    categories        text[],

    CONSTRAINT domains_state_check CHECK (state IN (
        'new', 'active', 'failing', 'down', 'unreachable',
        'no_sitemap', 'redirects', 'blocked', 'ineligible', 'excluded'))
);

-- Two tiers, so domains that already have URLs are refreshed before new ones are discovered.
CREATE INDEX IF NOT EXISTS domains_refresh_due_idx ON domains (next_due_at)
    WHERE state IN ('active', 'failing', 'down');
CREATE INDEX IF NOT EXISTS domains_discovery_due_idx ON domains (next_due_at, rank)
    WHERE state IN ('new', 'unreachable', 'no_sitemap', 'redirects', 'blocked', 'ineligible');
CREATE INDEX IF NOT EXISTS domains_categories_idx ON domains USING gin (categories);
CREATE INDEX IF NOT EXISTS domains_canonical_idx ON domains (canonical_host)
    WHERE canonical_host IS NOT NULL;

-- One row per source per label, so a refresh from one source never discards another's verdict.
CREATE TABLE IF NOT EXISTS domain_categories (
    host           text NOT NULL REFERENCES domains(host) ON DELETE CASCADE,
    source         text NOT NULL,
    category       text NOT NULL,
    raw_category   text,
    category_id    integer,
    super_category text,
    recorded_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (host, source, category)
);

CREATE INDEX IF NOT EXISTS domain_categories_category_idx ON domain_categories (category);

-- When each source last looked at a domain, whether or not it had anything to say.
CREATE TABLE IF NOT EXISTS category_checks (
    host       text NOT NULL REFERENCES domains(host) ON DELETE CASCADE,
    source     text NOT NULL,
    checked_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (host, source)
);

CREATE TABLE IF NOT EXISTS excluded_categories (
    category text PRIMARY KEY,
    reason   text NOT NULL
);

INSERT INTO excluded_categories (category, reason) VALUES
    ('adult',         'sexual content'),
    ('gambling',      'casinos and betting'),
    ('bank',          'login screens with nothing to index, and probing them reads as a scan'),
    ('malware',       'unsafe'),
    ('phishing',      'unsafe'),
    ('cryptojacking', 'unsafe'),
    ('stalkerware',   'unsafe'),
    ('ddos',          'unsafe'),
    ('hacking',       'unsafe'),
    ('warez',         'unlicensed distribution'),
    ('dangerous',     'instructions for causing harm'),
    ('dialer',        'unsafe'),
    ('cheating',      'academic fraud'),
    ('shortener',     'no content of its own'),
    ('redirector',    'no content of its own'),
    ('ads',           'advertising and tracking endpoints'),
    ('marketingware', 'advertising and tracking endpoints'),
    ('dynamic_dns',   'infrastructure, not a publisher'),
    ('doh',           'infrastructure, not a publisher'),
    ('proxy',         'infrastructure, not a publisher'),
    ('social',        'pages generated per user rather than published'),
    ('forums',        'pages generated per user rather than published'),
    ('chat',          'pages generated per user rather than published'),
    ('webmail',       'pages generated per user rather than published'),
    ('filehosting',   'pages generated per user rather than published')
ON CONFLICT (category) DO NOTHING;

-- One row per sitemap file, with what makes the next read of it cheap.
CREATE TABLE IF NOT EXISTS sitemaps (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host             text NOT NULL REFERENCES domains(host) ON DELETE CASCADE,
    url              text NOT NULL UNIQUE,
    kind             text,
    parent_id        bigint,
    depth            smallint NOT NULL DEFAULT 0,
    status           text NOT NULL DEFAULT 'ok',
    error            text,
    etag             text,
    last_modified    text,
    content_hash     text,
    url_count        integer NOT NULL DEFAULT 0,
    child_count      integer NOT NULL DEFAULT 0,
    trust            text NOT NULL DEFAULT 'unknown',
    index_lastmod    text,
    check_interval_s integer NOT NULL DEFAULT 86400,
    next_check_at    timestamptz,
    fetched_at       timestamptz,
    changed_at       timestamptz,
    CONSTRAINT sitemaps_status_check CHECK (status IN ('ok', 'error', 'gone')),
    CONSTRAINT sitemaps_trust_check CHECK (trust IN ('unknown', 'suspect', 'trusted', 'untrusted'))
);

CREATE INDEX IF NOT EXISTS sitemaps_host_idx ON sitemaps (host);

-- Exactly what is published: not known to be bad, and carrying no disqualifying category.
CREATE OR REPLACE VIEW published_domains AS
    SELECT host FROM domains
    WHERE state IN ('new', 'active', 'failing', 'no_sitemap')
      AND NOT (coalesce(categories, '{}') && ARRAY(SELECT category FROM excluded_categories))
    ORDER BY host;
