tweet1 = {
    "user": {
        "id": "1472303180033703944",
        "url": "https://x.com/Brett_Crypto_X",
        "name": "Brett",
        "username": "Brett_Crypto_X",
        "created_at": "Sat Dec 18 20:30:18 +0000 2021",
        "description": "Co Owner of https://t.co/v8VOfmCDOx 🔲 @BitrueOfficial ambassador. #XRP Keep your faith in Jesus and our father to Protect you.",
        "favourites_count": 169136,
        "followers_count": 83751,
        "listed_count": None,
        "media_count": 6927,
        "profile_image_url": "https://pbs.twimg.com/profile_images/1875592162710044672/wnrODvYG_normal.jpg",
        "profile_banner_url": None,
        "statuses_count": 52110,
        "verified": False,
        "is_blue_verified": None,
        "entities": None,
        "can_dm": None,
        "can_media_tag": None,
        "location": None,
        "pinned_tweet_ids": None,
    },
    "id": "1889336898767683906",
    "text": "Here is how $XRP will reach $10,000 per coin 👀 https://t.co/ELQFOYWQ5C",
    "reply_count": 402,
    "retweet_count": 1576,
    "like_count": 5871,
    "quote_count": 109,
    "bookmark_count": 2372,
    "url": "https://x.com/Brett_Crypto_X/status/1889336898767683906",
    "created_at": "Tue Feb 11 15:33:13 +0000 2025",
    "media": [
        {
            "media_url": "https://pbs.twimg.com/amplify_video_thumb/1889336819960922112/img/nG8WadUmBK0IUo6Z.jpg",
            "type": "video",
        }
    ],
    "is_quote_tweet": False,
    "is_retweet": False,
    "lang": None,
    "conversation_id": None,
    "in_reply_to_screen_name": None,
    "in_reply_to_status_id": None,
    "in_reply_to_user_id": None,
    "quoted_status_id": None,
    "quote": None,
    "display_text_range": None,
    "entities": None,
    "extended_entities": None,
}
